### ISSUE TITLE
Various Structure View issues

### ISSUE THREAD

**Issue by TianhongZhang** [tony-yuan/JsHELM#44]
Apply this notation to the canvas:
PEPTIDE1{A}|PEPTIDE2{A.G.C.H.H.[mD].G.F.C.E.E.R}$PEPTIDE2,PEPTIDE2,3:R3-9:R3|PEPTIDE1,PEPTIDE2,1:R2-6:R3$$$

Select the last three monomers (EER). we got overlapped structure in 'Structure View', which should be cleaned either locally in Java Script, or call into HELM2 service. 
![image](https://cloud.githubusercontent.com/assets/3718858/19032713/6d6c4a1e-8929-11e6-8a1f-7f8f0449acf6.png)

Select the four monomers at the branch point, only one monomer structure was displayed.
![image](https://cloud.githubusercontent.com/assets/3718858/19032807/d681964e-8929-11e6-82f3-e588b91fab65.png)

Select all monomers, only one monomer was displayed.
![image](https://cloud.githubusercontent.com/assets/3718858/19032864/137370b8-892a-11e6-8430-01ce7983d7b6.png)

**Comment by tony-yuan** [comment]
This is fixed in 2016-10-05 update.  When creating the App, *cleanupurl* parameter is for this purpose.  One example:

    <div id="div1"></div>
    <script type="text/javascript">
        var app;
        scil.ready(function () {
            app = new org.helm.webeditor.App("div1", { cleanupurl: "http://www.elncloud.com/helm/jsdraw/service.aspx?cmd=cleanup", .... });
        });
    </script>

**Comment by TianhongZhang** [comment]
Does this service "cmd=cleanup" exist in the AjaxTool in HELM2WebService?

**Comment by TianhongZhang** [comment]
First case fixed. Second and third case still show wrong structures.

**Comment by TianhongZhang** [comment]
confirm fix and close
